apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eureka
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  strategy: {}
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - image: ciberkleid/s1p-2020-mesh-eureka-server
          name: eureka
          resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue
  name: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  strategy: {}
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - image: ciberkleid/s1p-2020-mesh-blueorgreenservice
          name: blue
          env:
            - name: EUREKA_HOST
              value: eureka
            - name: EUREKA_CLIENT_HOST
              value: blue
            - name: COLOR
              value: blue
            - name: SERVER_PORT
              value: "8080"
          resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: green
  name: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green
  strategy: {}
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
        - image: ciberkleid/s1p-2020-mesh-blueorgreenservice
          name: green
          env:
            - name: EUREKA_HOST
              value: eureka
            - name: EUREKA_CLIENT_HOST
              value: green
            - name: COLOR
              value: green
            - name: SERVER_PORT
              value: "8080"
          resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: slowgreen
  name: slowgreen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slowgreen
  strategy: {}
  template:
    metadata:
      labels:
        app: slowgreen
    spec:
      containers:
        - image: ciberkleid/s1p-2020-mesh-blueorgreenservice
          name: slowgreen
          env:
            - name: EUREKA_HOST
              value: eureka
            - name: EUREKA_CLIENT_HOST
              value: slowgreen
            - name: COLOR
              value: green
            - name: SLOW
              value: "true"
            - name: SERVER_PORT
              value: "8080"
          resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yellow
  name: yellow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yellow
  strategy: {}
  template:
    metadata:
      labels:
        app: yellow
    spec:
      containers:
        - image: ciberkleid/s1p-2020-mesh-blueorgreenservice
          name: yellow
          env:
            - name: EUREKA_HOST
              value: eureka
            - name: EUREKA_CLIENT_HOST
              value: yellow
            - name: COLOR
              value: yellow
            - name: SPRING_PROFILES_ACTIVE
              value: "premium"
            - name: SERVER_PORT
              value: "8080"
          resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: ciberkleid/s1p-2020-mesh-blueorgreenfrontend
          name: frontend
          env:
            - name: EUREKA_HOST
              value: eureka
            - name: EUREKA_CLIENT_HOST
              value: frontend
            - name: SERVER_PORT
              value: "8080"
          resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy: {}
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - image: ciberkleid/s1p-2020-mesh-blueorgreengateway
          name: gateway
          env:
            - name: EUREKA_HOST
              value: eureka
            - name: EUREKA_CLIENT_HOST
              value: gateway
            - name: SERVER_PORT
              value: "8080"
          resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authgateway
  name: authgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authgateway
  strategy: {}
  template:
    metadata:
      labels:
        app: authgateway
    spec:
      containers:
        - image: ciberkleid/s1p-2020-mesh-authgateway
          name: authgateway
          env:
            - name: EUREKA_HOST
              value: eureka
            - name: EUREKA_CLIENT_HOST
              value: authgateway
          resources: {}
