apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka
  name: eureka
spec:
  ports:
    - name: 8761-8761
      port: 8761
      protocol: TCP
      targetPort: 8761
  selector:
    app: eureka
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue
  name: blue
spec:
  ports:
    - name: 8080-8080-blue
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: blue
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: green
  name: green
spec:
  ports:
    - name: 8080-8080-green
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: green
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: slowgreen
  name: slowgreen
spec:
  ports:
    - name: 8080-8080-slowgreen
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: slowgreen
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yellow
  name: yellow
spec:
  ports:
    - name: 8080-8080-yellow
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: yellow
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
    - name: 8080-8080-frontend
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: frontend
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  ports:
    - name: 8080-8080-gateway
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: gateway
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: authgateway
  name: authgateway
spec:
  ports:
    - name: 8080-8080-authgateway
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: authgateway
  type: LoadBalancer
status:
  loadBalancer: {}
