eureka:
  client:
    serviceUrl:
      defaultZone: http://${LOCALHOST:-localhost}:8761/eureka/
  instance:
    hostname: ${LOCALHOST:-localhost}
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
spring:
  application:
    name: blueorgreenauthgateway