spring:
  application:
    name: blueorgreen
  cloud:
    services:
      registrationMethod: direct


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    # Initially launch the service with the status of OUT_OF_SERVICE
#    initial-status: out_of_service

management:
  security:
    enabled: false
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    shutdown:
#      enabled: true

security:
  basic:
    enabled: false
server:
  port: 7070