
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:-localhost}:8761/eureka/
  instance:
    hostname: ${EUREKA_CLIENT_HOST:-localhost}
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
spring:
  application:
    name: blueorgreengateway
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
server:
  port: 8383

management:
  endpoints:
    web:
      exposure:
        include: "*"
#      base-path: /manage

