
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
spring:
  application:
    name: blueorgreengateway
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
server:
  port: 8383

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /manage
  endpoint:
    shutdown:
      enabled: true

