server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false

ribbon:
  eureka:
    enabled: false
  http:
    client:
      enabled: true
  # Default ReadTimeout=5000, ConnectTimeout=2000. Adding 5s to each for demo.
  # https://github.com/Netflix/ribbon/blob/master/ribbon-core/src/main/java/com/netflix/client/config/CommonClientConfigKey.java#L103
  ReadTimeout: 10000
  ConnectTimeout: 7000

colorServiceUrl: ${COLOR_SERVICE_URL}
