spring:
  application:
    name: blueorgreenfrontend
  cloud:
    services:
      registrationMethod: direct
server:
  port: 9090

security:
  basic:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:-localhost}:8761/eureka/
    register-with-eureka: ${EUREKA_REGISTER:-true}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:-true}
  instance:
    hostname: ${EUREKA_CLIENT_HOST:-localhost}
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

#removeTypeCookie: false