apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: blueorgreen
spec:
  host: blueorgreen
  trafficPolicy:
    tls:
      mode: DISABLE
  subsets:
  - name: basic
    labels:
      app: blueorgreen
      access: basic
  - name: premium
    labels:
      app: blueorgreen
