apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blueorgreen
    apptype: blue
    access: basic
  name: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blueorgreen
      apptype: blue
  strategy: {}
  template:
    metadata:
      labels:
        app: blueorgreen
        apptype: blue
        access: basic
    spec:
      containers:
      - image: marygabry1508/s1p-2020-mesh-blueorgreenservice
        name: blue
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "blue,istio"
        resources: {}
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blueorgreen
    apptype: green
    access: basic
  name: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blueorgreen
      apptype: green
  strategy: {}
  template:
    metadata:
      labels:
        app: blueorgreen
        apptype: green
        access: basic
    spec:
      containers:
      - image: marygabry1508/s1p-2020-mesh-blueorgreenservice
        name: green
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "green,istio"
        resources: {}
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blueorgreen
    apptype: orange
    access: basic
  name: orange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blueorgreen
      apptype: orange
  strategy: {}
  template:
    metadata:
      labels:
        app: blueorgreen
        apptype: orange
        access: basic
    spec:
      containers:
      - image: marygabry1508/s1p-2020-mesh-blueorgreenservice
        name: orange
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "orange,istio"
        - name: SLOW
          value: "true"
        resources: {}
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blueorgreen
    apptype: yellow
  name: yellow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blueorgreen
      apptype: yellow
  strategy: {}
  template:
    metadata:
      labels:
        app: blueorgreen
        apptype: yellow
    spec:
      containers:
        - image: marygabry1508/s1p-2020-mesh-blueorgreenservice
          name: yellow
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "yellow,istio"
          resources: {}
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    apptype: blueorgreen-fe
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      apptype: blueorgreen-fe
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
        apptype: blueorgreen-fe
    spec:
      containers:
      - image: marygabry1508/s1p-2020-mesh-blueorgreenfrontend
        name: frontend
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "istio"
        - name: COLOR_SERVICE_URL
          value: "http://blueorgreen.marygabry.name/blueorgreen"
        resources: {}
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authgateway
    apptype: blueorgreen-gw
  name: authgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authgateway
      apptype: blueorgreen-gw
  strategy: {}
  template:
    metadata:
      labels:
        app: authgateway
        apptype: blueorgreen-gw
    spec:
      containers:
      - image: marygabry1508/s1p-2020-mesh-authgateway
        name: authgateway
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "istio"
        - name: COLOR_APPLICATION_URL
          value: "http://blueorgreen.marygabry.name"
        resources: {}
        imagePullPolicy: Always