apiVersion: v1
kind: Service
metadata:
  labels:
    apptype: blueorgreen
  name: blueorgreen
spec:
  ports:
    - name: 8181-8181
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    access: basic
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    apptype: blueorgreen
  name: blueorgreen-premium
spec:
  ports:
  - name: 8181-8181
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    apptype: blueorgreen
  type: ClusterIP
status:
  loadBalancer: {}
